### PR TITLE
fix: max iterations for redis match functions

### PR DESCRIPTION
**Pull request by bryancua**
Introduces IterationLimit for redis match functions to stop infinite loop. 

Two potential infinite loops
- DeleteMatchFn 
- ScanAtLeast

### CODE REVIEW

**Comment by tmathews** [comment]
Is this really the solution to the infinite loop? I imagine it scans through all keys if they are null it's cause they don't match. Otherwise the redis calls should end when it's through everything. Maybe nothing is matching?

**Comment by bryancua** [comment]
> Is this really the solution to the infinite loop? I imagine it scans through all keys if they are null it's cause they don't match. Otherwise the redis calls should end when it's through everything. Maybe nothing is matching?

Redis won't know when to stop. The reason is that the COUNT that we pass into the SCAN function is the COUNT prior to pattern matching. Even if the loop isn't "infinite", if we need to go through *all* of the keys in the redis cache, we might be waiting too long. 

For example, when scanning for 100 entries of a certain pattern where only 3 (or none) exist, it will continue to attempt to scan until error / hit the end of the list of all keys. I haven't checked this for DeleteMatchKeyFn, but I assume the same could be true since it is using the same scan.

**Comment by tmathews** [comment]
That is the intended functionality of the SCAN method. We shouldn't implement magic functionality like this. If anything we should provide a option or new method which provides this option. I don't like that we are altering the intended functionality and setting it to an arbitrary value. For example we can add a method for ScanWithEscape which allows a value to be passed in which it escapes at.

**Review by tmathews — CHANGES_REQUESTED** [review]
See previous comment.

**Comment by bryancua** [comment]
> That is the intended functionality of the SCAN method. We shouldn't implement magic functionality like this. If anything we should provide a option or new method which provides this option. I don't like that we are altering the intended functionality and setting it to an arbitrary value. For example we can add a method for ScanWithEscape which allows a value to be passed in which it escapes at.

I've changed it to its own function.

**Review by tmathews — APPROVED** [review]
Yes, this is the way.

**Comment by bryancua** [comment]
> Yes, this is the way.

Thanks

**Pull request merged**
